# Generated by Django 6.0 on 2026-01-05 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.CharField(choices=[('notice', '공지'), ('event', '이벤트'), ('update', '업데이트')], default='notice', max_length=20, verbose_name='유형')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='상단고정')),
                ('is_published', models.BooleanField(default=True, verbose_name='공개')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항 목록',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='카테고리명')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='슬러그')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
            ],
            options={
                'verbose_name': '게시물 카테고리',
                'verbose_name_plural': '게시물 카테고리 목록',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100, verbose_name='용어')),
                ('definition', models.TextField(verbose_name='정의')),
                ('category', models.CharField(choices=[('rights', '권리분석'), ('procedure', '경매절차'), ('tax', '세금/비용'), ('legal', '법률용어'), ('general', '일반')], default='general', max_length=20, verbose_name='카테고리')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('related_terms', models.ManyToManyField(blank=True, to='info_center.glossaryterm', verbose_name='관련 용어')),
            ],
            options={
                'verbose_name': '용어',
                'verbose_name_plural': '용어사전',
                'ordering': ['category', 'order', 'term'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='슬러그')),
                ('thumbnail', models.ImageField(blank=True, upload_to='posts/', verbose_name='썸네일')),
                ('content', models.TextField(verbose_name='내용')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='요약')),
                ('author_name', models.CharField(blank=True, max_length=50, verbose_name='작성자명')),
                ('tags', models.CharField(blank=True, help_text='쉼표로 구분', max_length=200, verbose_name='태그')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('is_published', models.BooleanField(default=False, verbose_name='공개')),
                ('is_featured', models.BooleanField(default=False, verbose_name='메인 노출')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='발행일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='info_center.postcategory', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '게시물',
                'verbose_name_plural': '게시물 목록',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
