# Generated by Django 6.0 on 2026-01-05 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='이니셜 또는 가명', max_length=20, verbose_name='작성자')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='평점')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='후기 내용')),
                ('video_url', models.URLField(blank=True, help_text='유튜브 URL', verbose_name='영상 URL')),
                ('is_approved', models.BooleanField(default=False, verbose_name='승인')),
                ('is_featured', models.BooleanField(default=False, verbose_name='메인 노출')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='services.servicecategory', verbose_name='서비스 분야')),
            ],
            options={
                'verbose_name': '고객 후기',
                'verbose_name_plural': '고객 후기 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuccessCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('thumbnail', models.ImageField(upload_to='success_cases/', verbose_name='대표이미지')),
                ('property_type', models.CharField(max_length=50, verbose_name='물건유형')),
                ('location', models.CharField(max_length=100, verbose_name='소재지')),
                ('winning_price', models.BigIntegerField(verbose_name='낙찰가')),
                ('market_price', models.BigIntegerField(verbose_name='시세')),
                ('client_situation', models.TextField(verbose_name='고객 상황')),
                ('selection_reason', models.TextField(verbose_name='물건 선정 이유')),
                ('analysis_process', models.TextField(verbose_name='권리분석 과정')),
                ('bidding_strategy', models.TextField(verbose_name='입찰 전략')),
                ('result_summary', models.TextField(verbose_name='결과 및 수익')),
                ('is_featured', models.BooleanField(default=False, verbose_name='메인 노출')),
                ('is_published', models.BooleanField(default=True, verbose_name='공개')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='success_cases', to='services.servicecategory', verbose_name='서비스 분야')),
            ],
            options={
                'verbose_name': '성공사례',
                'verbose_name_plural': '성공사례 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
