# Generated by Django 6.0 on 2026-01-05 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='요금제명')),
                ('description', models.TextField(verbose_name='설명')),
                ('price_type', models.CharField(choices=[('fixed', '정액제'), ('rate', '정률제'), ('mixed', '정률+성공보수'), ('annual', '연간 계약제')], max_length=20, verbose_name='요금 유형')),
                ('price_display', models.CharField(max_length=100, verbose_name='요금 표시')),
                ('features', models.JSONField(default=list, verbose_name='서비스 내용')),
                ('target_customers', models.CharField(max_length=200, verbose_name='대상 고객')),
                ('is_popular', models.BooleanField(default=False, verbose_name='인기 요금제')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
            ],
            options={
                'verbose_name': '요금제',
                'verbose_name_plural': '요금제 목록',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='단계 번호')),
                ('title', models.CharField(max_length=100, verbose_name='단계명')),
                ('description', models.TextField(verbose_name='설명')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='아이콘')),
            ],
            options={
                'verbose_name': '프로세스 단계',
                'verbose_name_plural': '프로세스 단계 목록',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='서비스명')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='슬러그')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='아이콘 클래스')),
                ('short_description', models.CharField(max_length=200, verbose_name='간단 설명')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '서비스 카테고리',
                'verbose_name_plural': '서비스 카테고리 목록',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(upload_to='services/', verbose_name='대표 이미지')),
                ('overview', models.TextField(verbose_name='서비스 개요')),
                ('target_properties', models.TextField(verbose_name='대상 부동산')),
                ('target_customers', models.TextField(verbose_name='대상 고객')),
                ('process_steps', models.JSONField(default=list, verbose_name='업무 프로세스')),
                ('checkpoints', models.TextField(verbose_name='핵심 체크포인트')),
                ('benefits', models.TextField(blank=True, verbose_name='서비스 혜택')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='services.servicecategory', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '서비스 상세',
                'verbose_name_plural': '서비스 상세 목록',
            },
        ),
    ]
