# Generated by Django 6.0 on 2026-01-05 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='카테고리명')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='슬러그')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
            ],
            options={
                'verbose_name': '물건 카테고리',
                'verbose_name_plural': '물건 카테고리 목록',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, verbose_name='사건번호')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('property_type', models.CharField(choices=[('apartment', '아파트'), ('villa', '빌라/다세대'), ('house', '단독주택'), ('officetel', '오피스텔'), ('commercial', '상가'), ('office', '오피스'), ('factory', '공장'), ('warehouse', '창고'), ('land', '토지'), ('other', '기타')], max_length=20, verbose_name='물건유형')),
                ('address', models.CharField(max_length=300, verbose_name='주소')),
                ('sido', models.CharField(max_length=20, verbose_name='시도')),
                ('sigungu', models.CharField(max_length=20, verbose_name='시군구')),
                ('dong', models.CharField(blank=True, max_length=20, verbose_name='읍면동')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='위도')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='경도')),
                ('area_land', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='대지면적(㎡)')),
                ('area_building', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='건물면적(㎡)')),
                ('floor_info', models.CharField(blank=True, max_length=50, verbose_name='층수')),
                ('appraisal_price', models.BigIntegerField(verbose_name='감정가')),
                ('minimum_price', models.BigIntegerField(verbose_name='최저가')),
                ('market_price', models.BigIntegerField(blank=True, null=True, verbose_name='시세')),
                ('auction_date', models.DateField(verbose_name='입찰일')),
                ('auction_status', models.CharField(choices=[('scheduled', '입찰예정'), ('ongoing', '진행중'), ('completed', '완료'), ('cancelled', '취소')], default='scheduled', max_length=20, verbose_name='경매상태')),
                ('bid_count', models.PositiveIntegerField(default=0, verbose_name='유찰횟수')),
                ('court', models.CharField(blank=True, max_length=50, verbose_name='관할법원')),
                ('rights_analysis', models.TextField(verbose_name='권리분석 요약')),
                ('risk_level', models.CharField(choices=[('A', '안전'), ('B', '보통'), ('C', '주의')], default='B', max_length=1, verbose_name='리스크등급')),
                ('tenant_info', models.TextField(blank=True, verbose_name='임차인 현황')),
                ('special_conditions', models.TextField(blank=True, verbose_name='특이사항')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='추천물건')),
                ('is_weekly_pick', models.BooleanField(default=False, verbose_name='금주의 추천')),
                ('recommendation_reason', models.TextField(blank=True, verbose_name='추천 이유')),
                ('tags', models.CharField(blank=True, help_text='쉼표로 구분', max_length=200, verbose_name='태그')),
                ('thumbnail', models.ImageField(upload_to='properties/thumbnails/', verbose_name='대표이미지')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.propertycategory', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '경매 물건',
                'verbose_name_plural': '경매 물건 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/images/', verbose_name='이미지')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='설명')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='물건')),
            ],
            options={
                'verbose_name': '물건 이미지',
                'verbose_name_plural': '물건 이미지 목록',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PropertyBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='properties.property', verbose_name='물건')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '관심 물건',
                'verbose_name_plural': '관심 물건 목록',
                'unique_together': {('user', 'property')},
            },
        ),
    ]
