# Generated by Django 6.0 on 2026-01-05 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('phone', models.CharField(max_length=20, verbose_name='연락처')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('service_type', models.CharField(choices=[('home_buying', '내집마련 컨설팅'), ('redevelopment', '재개발/재건축 투자'), ('rental_income', '임대수익형 투자'), ('company_building', '사옥마련 컨설팅'), ('senior_facility', '노유자시설 컨설팅')], max_length=30, verbose_name='상담분야')),
                ('budget_range', models.CharField(blank=True, choices=[('under_1', '1억 이하'), ('1_to_3', '1~3억'), ('3_to_5', '3~5억'), ('5_to_10', '5~10억'), ('over_10', '10억 이상')], max_length=20, verbose_name='예산범위')),
                ('preferred_region', models.CharField(blank=True, max_length=100, verbose_name='희망지역')),
                ('message', models.TextField(blank=True, verbose_name='문의내용')),
                ('privacy_agreed', models.BooleanField(default=True, verbose_name='개인정보 수집동의')),
                ('marketing_agreed', models.BooleanField(default=False, verbose_name='마케팅 수신동의')),
                ('status', models.CharField(choices=[('pending', '접수대기'), ('contacted', '연락완료'), ('in_progress', '상담중'), ('completed', '상담완료'), ('contracted', '계약완료'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='상태')),
                ('admin_memo', models.TextField(blank=True, verbose_name='관리자 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='연락일')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_consultations', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
            ],
            options={
                'verbose_name': '상담신청',
                'verbose_name_plural': '상담신청 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
