# Generated by Django 6.0 on 2026-01-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', '일반'), ('service', '서비스'), ('payment', '결제'), ('consulting', '컨설팅'), ('academy', '아카데미')], default='general', max_length=20, verbose_name='카테고리')),
                ('question', models.CharField(max_length=300, verbose_name='질문')),
                ('answer', models.TextField(verbose_name='답변')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ 목록',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='부제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='배너 이미지')),
                ('link_url', models.URLField(blank=True, verbose_name='링크 URL')),
                ('link_text', models.CharField(default='자세히 보기', max_length=50, verbose_name='버튼 텍스트')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '히어로 배너',
                'verbose_name_plural': '히어로 배너 목록',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='협력사명')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='로고')),
                ('website', models.URLField(blank=True, verbose_name='웹사이트')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '협력사',
                'verbose_name_plural': '협력사 목록',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_consultations', models.PositiveIntegerField(default=0, verbose_name='총 컨설팅 건수')),
                ('total_winning_amount', models.BigIntegerField(default=0, verbose_name='누적 낙찰액')),
                ('total_customers', models.PositiveIntegerField(default=0, verbose_name='총 고객 수')),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='성공률')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트일')),
            ],
            options={
                'verbose_name': '사이트 통계',
                'verbose_name_plural': '사이트 통계',
            },
        ),
    ]
