# Generated by Django 6.0 on 2026-01-05 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='카테고리명')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='슬러그')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
            ],
            options={
                'verbose_name': '과정 카테고리',
                'verbose_name_plural': '과정 카테고리 목록',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='평점')),
                ('content', models.TextField(verbose_name='후기 내용')),
                ('is_approved', models.BooleanField(default=False, verbose_name='승인')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
            options={
                'verbose_name': '수강 후기',
                'verbose_name_plural': '수강 후기 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FreeLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('video_url', models.URLField(help_text='유튜브 URL', verbose_name='영상 URL')),
                ('thumbnail', models.ImageField(upload_to='academy/free/', verbose_name='썸네일')),
                ('duration', models.CharField(max_length=20, verbose_name='영상길이')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '무료 강좌',
                'verbose_name_plural': '무료 강좌 목록',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('photo', models.ImageField(upload_to='academy/instructors/', verbose_name='사진')),
                ('title', models.CharField(max_length=100, verbose_name='직함')),
                ('bio', models.TextField(verbose_name='소개')),
                ('specialties', models.CharField(max_length=200, verbose_name='전문분야')),
                ('teaching_history', models.TextField(blank=True, verbose_name='강의 이력')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '강사',
                'verbose_name_plural': '강사 목록',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='과정명')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='부제목')),
                ('thumbnail', models.ImageField(upload_to='academy/courses/', verbose_name='대표이미지')),
                ('duration', models.CharField(max_length=50, verbose_name='기간')),
                ('schedule', models.CharField(max_length=100, verbose_name='일정')),
                ('start_date', models.DateField(verbose_name='개강일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종강일')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='장소')),
                ('max_students', models.PositiveIntegerField(verbose_name='정원')),
                ('current_students', models.PositiveIntegerField(default=0, verbose_name='현재 신청인원')),
                ('price', models.PositiveIntegerField(verbose_name='정가')),
                ('discount_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='할인가')),
                ('description', models.TextField(verbose_name='과정 소개')),
                ('curriculum', models.JSONField(default=list, verbose_name='커리큘럼')),
                ('target_audience', models.TextField(verbose_name='대상 수강생')),
                ('benefits', models.TextField(blank=True, verbose_name='수강 혜택')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('is_enrolling', models.BooleanField(default=True, verbose_name='모집중')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academy.coursecategory', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '교육 과정',
                'verbose_name_plural': '교육 과정 목록',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('phone', models.CharField(max_length=20, verbose_name='연락처')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('payment_method', models.CharField(choices=[('card', '신용카드'), ('bank', '계좌이체'), ('installment', '분할결제')], max_length=20, verbose_name='결제방법')),
                ('payment_status', models.CharField(choices=[('pending', '결제대기'), ('completed', '결제완료'), ('cancelled', '결제취소'), ('refunded', '환불완료')], default='pending', max_length=20, verbose_name='결제상태')),
                ('payment_amount', models.PositiveIntegerField(verbose_name='결제금액')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='결제일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academy.course', verbose_name='과정')),
            ],
            options={
                'verbose_name': '수강신청',
                'verbose_name_plural': '수강신청 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
