# Generated by Django 6.0 on 2026-01-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('value', models.CharField(max_length=50, verbose_name='수치')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='단위')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='아이콘')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
            ],
            options={
                'verbose_name': '사업 실적',
                'verbose_name_plural': '사업 실적 목록',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceo_greeting', models.TextField(verbose_name='대표 인사말')),
                ('vision', models.TextField(verbose_name='비전')),
                ('mission', models.TextField(verbose_name='미션')),
                ('ceo_name', models.CharField(blank=True, max_length=50, verbose_name='대표자명')),
                ('ceo_photo', models.ImageField(blank=True, upload_to='company/', verbose_name='대표자 사진')),
            ],
            options={
                'verbose_name': '회사 정보',
                'verbose_name_plural': '회사 정보',
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('position', models.CharField(max_length=100, verbose_name='직책')),
                ('photo', models.ImageField(upload_to='experts/', verbose_name='사진')),
                ('specialty', models.CharField(max_length=200, verbose_name='전문분야')),
                ('certifications', models.TextField(blank=True, verbose_name='자격증')),
                ('career', models.TextField(blank=True, verbose_name='경력사항')),
                ('introduction', models.TextField(blank=True, verbose_name='소개')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '전문가',
                'verbose_name_plural': '전문가 목록',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='연도')),
                ('month', models.PositiveIntegerField(blank=True, null=True, verbose_name='월')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '연혁',
                'verbose_name_plural': '연혁 목록',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='지점명')),
                ('address', models.CharField(max_length=300, verbose_name='주소')),
                ('phone', models.CharField(max_length=20, verbose_name='전화번호')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='팩스')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='위도')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='경도')),
                ('parking_info', models.TextField(blank=True, verbose_name='주차안내')),
                ('is_main', models.BooleanField(default=False, verbose_name='본사')),
            ],
            options={
                'verbose_name': '오피스 위치',
                'verbose_name_plural': '오피스 위치 목록',
            },
        ),
    ]
